version: '3'

services:
  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: guilhermegs/node
    container_name: app
    networks:
      - nodenet
    ports:
      - "3000:3000"
    tty: true

  db:
    image: mysql:latest
    # command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_DATABASE: nodedb
    networks:
      - nodenet
    

networks:
  nodenet:
    driver: bridge


